module
public import VersoManual
public meta import Verso.Doc.Elab.Monad

/-! Site-owned Verso extension of the rule reference: a fenced `html` code block inserts
markup that the root package's generator escaped and admitted (`Regula.Site.htmlBlock`), and
the theme script. The stylesheet is generated by the root package from its colour tokens
(`RegulaCore.SiteTheme`) into `Generated/regula.css`, which `Main` links from every page.

The theme script is inlined into every page's `<head>` (Verso's `extraJs`), so the stored
colour-theme choice applies before the first paint. It adds the Light/Dark/System control and
a `/` shortcut to search, and patches three accessibility defects of Verso's page template
(`lang`, zoom lock, unnamed table-of-contents toggles) and one of its search box (an
`aria-expanded` state on a `searchbox` role) until they are fixed upstream. Without
JavaScript the pages follow the operating system's light or dark setting and show no control. -/

public section
open Lean Elab
open Verso ArgParse Doc Elab Genre.Manual Html
open Verso.Output (Html)

namespace RegulaSite

/-- The colour-theme control and the template stopgaps. States: `system` (the default; stores
nothing), `light` and `dark`, kept under a site-specific `localStorage` key because the origin
is shared with other GitHub Pages sites. Every storage access tolerates blocked storage. -/
def themeScript : String := r##"
(function () {
  var KEY = "regula-theme";
  var root = document.documentElement;
  var current = "system";
  try {
    var saved = localStorage.getItem(KEY);
    if (saved === "light" || saved === "dark") current = saved;
  } catch (_) {}
  function apply() {
    if (current === "system") root.removeAttribute("data-theme"); else root.setAttribute("data-theme", current);
  }
  apply();

  // Stopgaps for Verso's page template: the page language, and a viewport that allows zoom.
  root.lang = "en";
  var viewport = document.querySelector('meta[name="viewport"]');
  if (viewport) viewport.setAttribute("content", "width=device-width, initial-scale=1");

  var LABEL = { light: "Light theme", dark: "Dark theme", system: "System theme" };
  var ICON = {
    light: '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" aria-hidden="true"><circle cx="12" cy="12" r="4"/><path d="M12 2v2M12 20v2M4.9 4.9l1.4 1.4M17.7 17.7l1.4 1.4M2 12h2M20 12h2M4.9 19.1l1.4-1.4M17.7 6.3l1.4-1.4"/></svg>',
    dark: '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><path d="M20 14.5A8 8 0 0 1 9.5 4 8 8 0 1 0 20 14.5Z"/></svg>',
    system: '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><rect x="3" y="4" width="18" height="12" rx="2"/><path d="M8 20h8M12 16v4"/></svg>'
  };
  function sync() {
    var buttons = document.querySelectorAll(".rg-theme button");
    for (var i = 0; i < buttons.length; i++)
      buttons[i].setAttribute("aria-pressed", String(buttons[i].getAttribute("data-choice") === current));
  }
  function choose(t) {
    current = t;
    try { if (t === "system") localStorage.removeItem(KEY); else localStorage.setItem(KEY, t); } catch (_) {}
    apply(); sync();
  }
  function control() {
    var group = document.createElement("div");
    group.className = "rg-theme";
    group.setAttribute("role", "group");
    group.setAttribute("aria-label", "Colour theme");
    ["light", "dark", "system"].forEach(function (t) {
      var b = document.createElement("button");
      b.type = "button";
      b.setAttribute("data-choice", t);
      b.title = LABEL[t];
      b.setAttribute("aria-label", LABEL[t]);
      b.innerHTML = ICON[t];
      b.addEventListener("click", function () { choose(t); });
      group.appendChild(b);
    });
    return group;
  }

  // Another tab changed the choice.
  window.addEventListener("storage", function (e) {
    if (e.key !== KEY) return;
    current = e.newValue === "light" || e.newValue === "dark" ? e.newValue : "system";
    apply(); sync();
  });

  // "/" focuses the search box unless the reader is typing.
  document.addEventListener("keydown", function (e) {
    if (e.key !== "/" || e.ctrlKey || e.metaKey || e.altKey) return;
    var t = e.target;
    if (t && (t.isContentEditable || /^(INPUT|TEXTAREA|SELECT)$/.test(t.tagName))) return;
    var box = document.getElementById("cb1-input");
    if (box) { e.preventDefault(); box.focus(); }
  });

  document.addEventListener("DOMContentLoaded", function () {
    var header = document.querySelector("header");
    var drawer = document.querySelector("#toc .last");
    if (drawer) drawer.appendChild(control());
    if (header) header.appendChild(control());
    sync();
    // Stopgap: name Verso's table-of-contents toggles.
    var toc = document.getElementById("toggle-toc");
    if (toc && !toc.hasAttribute("aria-label")) toc.setAttribute("aria-label", "Show the table of contents");
    var toggles = document.querySelectorAll("input.toggle-split-toc");
    for (var i = 0; i < toggles.length; i++) {
      var title = toggles[i].closest(".title");
      var name = title ? title.textContent.trim() : "";
      if (!toggles[i].hasAttribute("aria-label")) toggles[i].setAttribute("aria-label", "Show or hide " + (name || "this part of the contents"));
    }
    // Verso adds its search box to the header on "load" (this listener runs after its own):
    // keep the theme control after it, so the tab order is the visual order, and give the
    // box the combobox role that its aria-expanded state belongs to.
    window.addEventListener("load", function () {
      var group = header && header.querySelector(":scope > .rg-theme");
      if (group) header.appendChild(group);
      var box = document.getElementById("cb1-input");
      if (box && box.getAttribute("role") === "searchbox") box.setAttribute("role", "combobox");
    });
  });
})();
"##

block_extension Block.rawHtml (html : String) where
  data := Json.str html
  traverse _ _ _ := pure none
  toHtml :=
    some <| fun _ _ _ data _ => do
      let .str html := data
        | reportError "Expected string JSON for raw HTML" *> pure .empty
      pure (Html.text false html)
  toTeX := none

/-- A fenced `html` block: its contents are inserted verbatim into the HTML output. Only the
root generator writes such blocks, from escaped data. -/
@[code_block]
meta def html : CodeBlockExpanderOf Unit
  | (), str => ``(Verso.Doc.Block.other (Block.rawHtml $(quote str.getVersoCodeBlock)) #[])

end RegulaSite
